
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Feb  3 2024 10:53:10 EST (Feb  3 2024 15:53:10 UTC)

// Verification Directory fv/counter 

module counter(out, enable, clk, reset);
  input enable, clk, reset;
  output [7:0] out;
  wire enable, clk, reset;
  wire [7:0] out;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_9;
  wire n_10, n_12, n_13, n_14, n_15, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38;
  DFRQJI3VX2 \out_reg[7] (.C (clk), .D (n_38), .Q (out[7]));
  DFRQJI3VX2 \out_reg[6] (.C (clk), .D (n_37), .Q (out[6]));
  NO2JI3VX0 g187__2398(.A (reset), .B (n_36), .Q (n_38));
  AN21JI3VX1 g190__5107(.A (n_35), .B (n_0), .C (reset), .Q (n_37));
  AN22JI3VX1 g189__6260(.A (n_33), .B (enable), .C (out[7]), .D (n_6),
       .Q (n_36));
  DFRQJI3VX2 \out_reg[5] (.C (clk), .D (n_34), .Q (out[5]));
  ON211JI3VX1 g193__4319(.A (n_29), .B (out[6]), .C (n_32), .D
       (enable), .Q (n_35));
  AN21JI3VX1 g194__8428(.A (n_31), .B (n_2), .C (reset), .Q (n_34));
  EN2JI3VX0 g191__5526(.A (out[7]), .B (n_32), .Q (n_33));
  DFRQJI3VX2 \out_reg[4] (.C (clk), .D (n_30), .Q (out[4]));
  ON211JI3VX1 g196__6783(.A (n_25), .B (out[5]), .C (n_28), .D
       (enable), .Q (n_31));
  AN21JI3VX1 g199__3680(.A (n_27), .B (n_3), .C (reset), .Q (n_30));
  NA2JI3VX0 g197__1617(.A (n_29), .B (out[6]), .Q (n_32));
  DFRQJI3VX2 \out_reg[3] (.C (clk), .D (n_26), .Q (out[3]));
  INJI3VX0 g198(.A (n_28), .Q (n_29));
  ON211JI3VX1 g201__2802(.A (n_21), .B (out[4]), .C (n_24), .D
       (enable), .Q (n_27));
  AN21JI3VX1 g204__1705(.A (n_23), .B (n_7), .C (reset), .Q (n_26));
  NA2JI3VX0 g202__5122(.A (n_25), .B (out[5]), .Q (n_28));
  DFRQJI3VX2 \out_reg[2] (.C (clk), .D (n_22), .Q (out[2]));
  INJI3VX0 g203(.A (n_24), .Q (n_25));
  ON211JI3VX1 g206__8246(.A (n_17), .B (out[3]), .C (n_20), .D
       (enable), .Q (n_23));
  AN21JI3VX1 g209__7098(.A (n_19), .B (n_1), .C (reset), .Q (n_22));
  NA2JI3VX0 g207__6131(.A (n_21), .B (out[4]), .Q (n_24));
  DFRQJI3VX2 \out_reg[1] (.C (clk), .D (n_18), .Q (out[1]));
  INJI3VX0 g208(.A (n_20), .Q (n_21));
  ON211JI3VX1 g211__1881(.A (n_12), .B (out[2]), .C (n_15), .D
       (enable), .Q (n_19));
  AN21JI3VX1 g214__5115(.A (n_13), .B (n_5), .C (reset), .Q (n_18));
  NA2JI3VX0 g212__7482(.A (n_17), .B (out[3]), .Q (n_20));
  DFRQJI3VX2 \out_reg[0] (.C (clk), .D (n_14), .Q (out[0]));
  INJI3VX0 g213(.A (n_15), .Q (n_17));
  NO2JI3VX0 g219__4733(.A (reset), .B (n_9), .Q (n_14));
  ON211JI3VX1 g216__6161(.A (out[0]), .B (out[1]), .C (n_10), .D
       (enable), .Q (n_13));
  NA2JI3VX0 g217__9315(.A (n_12), .B (out[2]), .Q (n_15));
  INJI3VX0 g218(.A (n_10), .Q (n_12));
  EN2JI3VX0 g220__9945(.A (enable), .B (out[0]), .Q (n_9));
  NA2JI3VX0 g221__2883(.A (out[3]), .B (n_6), .Q (n_7));
  NA2JI3VX0 g222__2346(.A (out[1]), .B (n_6), .Q (n_5));
  NA2JI3VX0 g223__1666(.A (out[4]), .B (n_6), .Q (n_3));
  NA2JI3VX0 g226__7410(.A (out[5]), .B (n_6), .Q (n_2));
  NA2JI3VX0 g225__6417(.A (out[2]), .B (n_6), .Q (n_1));
  NA2JI3VX0 g224__5477(.A (out[6]), .B (n_6), .Q (n_0));
  NA2JI3VX0 g227__2398(.A (out[0]), .B (out[1]), .Q (n_10));
  INJI3VX0 g232(.A (enable), .Q (n_6));
endmodule

